project:
  type: website
  output-dir: ./docs

website:
  title: "Pamir split intransitivity"
  navbar:
    left:
      - text: "Features"
        icon: fa-atlas
        href: ./features.html

format: 
  html:
    theme: litera

editor: visual

